services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: thepetz-backend-db
    environment:
      MYSQL_DATABASE: 'db_chat'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
